spring:
  application:
    name: spring-training

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # ← DBのURL。作成したDB名を指定する。（デフォルトで作成済みのDBはpostgres）
    username: postgres  # ← DBのログインユーザー
    password: password  # ← DBのログインパスワード
    driver-class-name: org.postgresql.Driver  # JDBCドライバのクラス名

  sql:
    init:
      mode: always  # ← これを設定すると、起動時に毎回 schema.sql → data.sql が自動的に実行される。

logging:
  level:
    # 実際に実行されるSQLが確認できる
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    # プレースホルダにバインドしてる値を確認できる
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE